# Menus
menu:
  首页: /
  归档: /archives
  分类: /categories
  标签: /tags
  关于: /about

# Customize
customize: # 首先修改这项里面的信息为你自己的各项信息
    logo:
        enabled: true
        width: 40
        height: 40
        url: //odqwjjp9p.qnssl.com/kb/logo.png
    profile:
        enabled: false # Whether to show profile bar
        avatar: # css/images/avatar.png
        gravatar: sunjichao.cn@gmail.com # Gravatar email address, if you enable Gravatar, your avatar config will be overriden
        author: Sun JiChao
        author_title: Programmer
        location: Dalian, China
        follow: https://github.com/sun-jichao/
    highlight: monokai
    sidebar: left # 侧边栏的所在位置，默认左边, options: left, right
    category_perExpand: false # 侧边栏里的各个分类是否默认展开
    thumbnail: true # enable posts thumbnail, options: true, false
    favicon: //odqwjjp9p.qnssl.com/kb/favicon.ico # path to favicon
    default_index_file: index.md # 是否指定一篇文章作为首页来代替默认的多篇文章的首页
    social_links:
        github: https://github.com/sun-jichao/KB-Site
        stack-overflow: #http://stackoverflow.com/users/7277090/zthxxx?tab=profile
        codepen: #http://codepen.io/zthxxx/
        rss: /atom.xml
    social_link_tooltip: true # enable the social link tooltip, options: true, false

# Widgets
widgets: # 挂件，默认指开启了分类这一栏
    - category
    # - recent_posts
    # - archive
    # - tag
    # - tagcloud
    # - links

# Excerpt
## Auto creat excerpt with not <!--more-->
## Enable will truncate auto_excerpt.lines rows in post head to replace excerpt.
auto_excerpt:
    enable: true
    lines: 5

# Search
search:
    insight: true # you need to install `hexo-generator-json-content` before using Insight Search
    swiftype: # enter swiftype install key here
    baidu: false # you need to disable other search engines to use Baidu search, options: true, false

# History version
history_control: # 启用这一项使得 wiki 能有历史版本的功能（查看源码、在线编辑、对比历史变动）
    enable: true
    server_link: https://github.com # 版本控制服务器，推荐使用 GitHub https://github.com
    user: sun-jichao # your GitHub name
    repertory: KB-Site # your repertory name of this wiki source code
    branch: writing # branch name of this wiki site source code

# Comment
comment:
    disqus: # enter disqus shortname here
    duoshuo: # enter duoshuo shortname here
    youyan: # enter youyan uid here

# Share
share: default # options: jiathis, bdshare, addtoany, default

# Plugins
plugins:
    lightgallery: true # options: true, false
    justifiedgallery: true # options: true, false
    google_analytics: # enter the tracking ID for your Google Analytics
    google_site_verification: # enter Google site verification code
    baidu_analytics: # enter Baidu Analytics hash key

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
    links:
